<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Model;

use App\Domain\Model\Generated\BaseEmployee;

/**
 * The Employee class maps the 'employees' table in database.
 */
class Employee extends BaseEmployee
{
}
