<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace App\Domain\Dao;

use App\Domain\Dao\Generated\BaseEmployeeDao;

/**
 * The EmployeeDao class will maintain the persistence of Employee class into the employees table.
 */
class EmployeeDao extends BaseEmployeeDao
{
}
